### ISSUE TITLE
PreparedStatement.setNull fails, missing tests for all types

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast-jdbc#47]
The following test:
```java
    @Test
    void testNull() throws SQLException {
        Connection connection = DriverManager.getConnection(JDBC_HAZELCAST_LOCALHOST);
        PreparedStatement statement = connection.prepareStatement("SELECT * FROM person WHERE name=?");
        statement.setNull(1, Types.VARCHAR);
        ResultSet rs = statement.executeQuery();
        assertFalse(rs.next());
    }
```
fails with:
```
java.sql.SQLException
	at com.hazelcast.jdbc.JdbcStatement.doExecute(JdbcStatement.java:409)
	at com.hazelcast.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:56)
	at com.hazelcast.jdbc.JdbcPreparedStatementTest.testNull(JdbcPreparedStatementTest.java:90)
        ...
Caused by: com.hazelcast.sql.HazelcastSqlException
	at com.hazelcast.sql.impl.QueryUtils.toPublicException(QueryUtils.java:78)
	at com.hazelcast.sql.impl.client.SqlClientService.rethrow(SqlClientService.java:287)
	at com.hazelcast.sql.impl.client.SqlClientService.rethrow(SqlClientService.java:278)
	at com.hazelcast.sql.impl.client.SqlClientService.execute(SqlClientService.java:115)
	at com.hazelcast.jdbc.HazelcastSqlClient.execute(HazelcastSqlClient.java:37)
	at com.hazelcast.jdbc.JdbcStatement.doExecute(JdbcStatement.java:400)
	... 67 more
Caused by: java.lang.NullPointerException
	at com.hazelcast.client.impl.protocol.codec.builtin.DataCodec.encode(DataCodec.java:32)
	at com.hazelcast.client.impl.protocol.codec.builtin.ListMultiFrameCodec.encode(ListMultiFrameCodec.java:42)
	at com.hazelcast.client.impl.protocol.codec.SqlExecuteCodec.encodeRequest(SqlExecuteCodec.java:109)
	at com.hazelcast.sql.impl.client.SqlClientService.execute(SqlClientService.java:91)
	... 69 more```
```
We also miss a test for all supported types in `JdbcPreparedStatement` (related to #8)

**Comment by SeriyBg** [comment]
Fixed by #52
